### ISSUE TITLE
gxkb rewrites xmodmap mappings

### ISSUE THREAD

**Issue by last5bits** [zen-tools/gxkb#10]
Hi everybody,

First, let me thank you for this tray indicator, I've been using it for awhile and it worked great. Here's, however, a small issue I've encountered.

Reproduce:
1. Run `xmodmap -e "keycode 117 = Prior" -e "keycode 112 = Next"` to swap PageUp and PageDown
2. Run `gxkb` and that will restore the mappings to the default

**Comment by zen-tools** [comment]
Hi! And thanks for the report.

I think there are three options to resolve this issue:

1. Run xmodmap after gxkb startup.

or

2. Set never_modify_config param to true in ~/.config/gxkb/gxkb.cfg. In this case gxkb will not override X keyboard config. But all keyboard layouts should be configured on X11 side.

or

3. Create your own keyboard layout. But it's more complex task.

**Comment by last5bits** [comment]
Thanks for the swift response! Unfortunately, solution 1 doesn't work since if you go to a TTY and back, the parameters still will be overridden. However, I tried solution 2 and it works like a charm. Thank you!

**Comment by last5bits** [comment]
That's interesting, opening a TTY and going back still overrides the mappings. Do you have any suggestions?

**Comment by zen-tools** [comment]
Looks like last bug was introduced by this [commit](https://github.com/zen-tools/gxkb/commit/9a0aeaf2ee4dfa2d2ec012b23a98db7248bd48c7). I have pushed a fix into the master branch. So, I will be grateful if you test it. Or you can try to rollback on gxkb v0.7.8 and I double check the fix later.

**Comment by last5bits** [comment]
Works for me! Thank you very much.
