### ISSUE TITLE
Missed flag for cz_qwerty layout

### ISSUE THREAD

**Issue by sv0** [zen-tools/gxkb#11]
I use following layouts:

    us,cz_qwerty,ua(unicode)

When the **cz_qwerty** layout is active I see a questin mark instead of flag:

![cz_qwerty](https://cloud.githubusercontent.com/assets/233977/26300445/652654c4-3ede-11e7-8a1b-cc968bc35d9a.png)

To fix it I just create a symlink  **cz_qwerty.png → cz.png**

    sudo ln -s /usr/share/gxkb/flags/cz.png /usr/share/gxkb/flags/cz_qwerty.png

![cz_qwerty_fixed](https://cloud.githubusercontent.com/assets/233977/26300898/c013b358-3edf-11e7-946c-aca38c2b5b32.png)

**Comment by zen-tools** [comment]
Hi! Thanks for the report. Now it's fixed.
