### ISSUE TITLE
Amount of layouts?

### ISSUE THREAD

**Issue by danlmc** [zen-tools/gxkb#12]
Hi Zen. Thanks for your work!

Can only three layouts be used at one time? I was trying to add more than three, but it doesn't seem to work.

Thank you!

**Comment by zen-tools** [comment]
Hi, @danlmc!

Due to X11 protocol limitation, you can use up to 4 layouts.

Here is a link with details:
https://bugs.freedesktop.org//show_bug.cgi?id=19501

**Comment by danlmc** [comment]
Thank you zen! I wasn't aware of that bug...thank you. If I use only three on gxkb, it works flawlessly, but if I add a fourth layout, it ceases to function at all. I'm not complaining...your work is amazing and much appreciated! Just giving you information from my experience. Thanks again!
