### ISSUE TITLE
 With the latest update missing language flag in Unity panel display

### ISSUE THREAD

**Issue by ghost** [zen-tools/gxkb#2]
Hello! I use Ubuntu 16.04.1 x64 with Unity as the desktop manager. After missing the last update the display of flags in the panel running programs. The program starts and runs in the background, but the lack of indication does not make the work more comfortable. I hope this is a bug, not a purposeful innovation.

**Comment by zen-tools** [comment]
Hi! Can you please show output of the **gxkb -v** command?

**Comment by ghost** [comment]
No problem

```
gxkb -v
gxkb version 0.7.8
Features:
AppIndicator support - No
```

**Comment by zen-tools** [comment]
I have fixed a build depends. Please, check the last gxkb build from ppa.

**Comment by ghost** [comment]
I use PPA `zen-root-gxkb-stable/now` and then I type in terminal `sudo apt-get upgrade gxkb`. The terminal provides`gxkb is already the newest version (0.7.8 + git19-0 ~ ubuntu16.04.1)` and, accordingly, no updates tightens. I tried to reinstall the package through synaptic result is the same.

**Comment by zen-tools** [comment]
Did you try to run **sudo apt-get update** and then **sudo apt-get apt-get upgrade gxkb**? The latest version is 0.7.8+git20-0.

**Comment by ghost** [comment]
Yes is first needed to update the package sources. Now the package has been updated indicator is displayed in the panel the problem is solved. Thank you for the quick help! The problem can be closed. Thank you!

**Comment by zen-tools** [comment]
Cool! :)
