### ISSUE TITLE
`xdotool key Control+v` with ru layout cause infinite layout switching loop

### ISSUE THREAD

**Issue by crabvk** [zen-tools/gxkb#20]
**xdotool** version 3.20160805.1
**gxkb** version 0.8.1

*/etc/X11/xorg.conf.d/00-keyboard.conf*
```
# Written by systemd-localed(8), read by systemd-localed and Xorg. It's
# probably wise not to edit this file manually. Use localectl(1) to
# instruct systemd-localed to update it.
Section "InputClass"
        Identifier "system-keyboard"
        MatchIsKeyboard "on"
        Option "XkbLayout" "us,ru"
        Option "XkbModel" "pc104"
        Option "XkbOptions" "grp:shifts_toggle"
EndSection
```
**Steps to reproduce:**
1. Switch to ru layout
2. Run `xdotool key --clearmodifiers Control+v`

Without gxkb running xdotool switches layout to us then back to ru only once.

**Comment by zen-tools** [comment]
Yeah, I can reproduce this issue, but only on desktop. And that is strange... I am not sure where is exactly a problem - in gxkb or in libxklavier. But I will check it later.

**Comment by zen-tools** [comment]
I have made a minimal working [application](https://gist.github.com/zen-tools/290edbc51849204ba717ed4708153123) to check if this is a bug in libxklavier. And the issue is fully [reproducible](https://tube.tchncs.de/videos/watch/440b00ae-1cd9-4c74-a963-b09331966ab8).
So, it's not a gxkb issue.

**Comment by crabvk** [comment]
OK, thank you.

**Comment by zen-tools** [comment]
No problems. I have sent an email to Sergey V. Udaltsov to discuss this issue. And if there will be any feedback, I will post an update here.

**Comment by zen-tools** [comment]
Seems like libxklavier project is abandoned. The last commit was made 6 years ago. Plus 5 months ago git repository was moved into the archive. I will investigate what to do next.
