### ISSUE TITLE
Spanish accents are backwards

### ISSUE THREAD

**Issue by noraatfedora** [zen-tools/gxkb#21]
When I switch to the Spanish keyboard layout, my accents show up as à è ì ò ù, when in reality it should be á é í ó ú. Is this a problem with gxkb or something else? I'm running Mint 19.2, with i3 as my WM.

**Comment by zen-tools** [comment]
Hi! I think, it's not a gxkb issue, because gxkb just switching keyboard layout in Xorg. But I guess, there should be some specific options for setxkbmap to change this behavior.
