### ISSUE TITLE
Remember layout for each window

### ISSUE THREAD

**Issue by kzkin** [zen-tools/gxkb#22]
request feature

**Comment by zen-tools** [comment]
There is a group_policy parameter in ~/.config/gxkb/gxkb.cfg file.
```
$ head -2 ~/.config/gxkb/gxkb.cfg 
[xkb config]
group_policy=2
```
You can change it value to:
0 - one common layout for all windows
1 - per window
2 - per application

And restart gxkb to apply new config changes.

**Comment by kzkin** [comment]
It would be nice to add a description of the configuration file parameters in the man page

**Comment by dpvpro** [comment]
Goof feature
