### ISSUE TITLE
FTBFS with gcc-10

### ISSUE THREAD

**Issue by mati75** [zen-tools/gxkb#23]
gxkb has fail to build from source with gcc-10 on Debian unstable. Full info https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=957325

**Comment by zen-tools** [comment]
Hi, Mateusz!

Thanks for the report, the issue should be fixed in commit ca3d6fd533

**Comment by mati75** [comment]
Hello Zen! Yes, it's working. спасибо

**Comment by zen-tools** [comment]
nie ma za co 😊
