### ISSUE TITLE
gxkb hungs

### ISSUE THREAD

**Issue by aloneuser** [zen-tools/gxkb#32]
Gxkb hungs when trying to switch layouts under heavy load and at the same time begins to heavily load the processor itself. This does not always happen in such conditions. I was deleting settings in ~/.config and ~/.local but it did not help. It never happened before. I temporarily returned to fbxkb

In Russian.
Gxkb зависает при попытке переключения раскладки, когда компьютер сильно загружен, и после зависания сам начинает сильно грузить процессор. Так бывает не всегда в таких условиях. Я удалял настройки в ~ / .config и ~ / .local, но это не помогло. Раньше такого не было. Я временно(надеюсь) вернулся на fbxkb.

**Comment by zen-tools** [comment]
Hi! What's a version of gxkb do you use?

In Ukrainian.
Привіт! Бачу, ти з України, можемо й українською поспілкуватись. Отже, яка в тебе версія gxkb?

**Comment by aloneuser** [comment]
Привіт! 
Я не пам'ятаю бо давно перейшов на fbxkb+xneur (бо gxneur повільно перемикае прапорці).
Нещодавно налаштовував xneur, та згадав що треба повідомити про баг.

> Hi! What's a version of gxkb do you use?
> 
> In Ukrainian.
> Привіт! Бачу, ти з України, можемо й українською поспілкуватись. Отже, яка в тебе версія gxkb?
>

**Comment by zen-tools** [comment]
Ага, зрозуміло. Думаю, що ця помилка була виправлена починаючи з версії 0.8.2 комітом 286fe1e.

Якщо буде час та натхнення перевірити, буду радий почути чи ця помилка нарешті виправлена. :slightly_smiling_face: Issue я наразі закриваю, то ж якщо що, можеш його перевідкрити чи створити нове.

**Comment by aloneuser** [comment]
Це версія 0.7.8-1 в репах Дебіана 9.

> Ага, зрозуміло. Думаю, що ця помилка була виправлена починаючи з версії 0.8.2 комітом 2d55f51.
> 
> Якщо буде час та натхнення перевірити, буду радий почути чи ця помилка нарешті виправлена. :slightly_smiling_face: Issue я наразі закриваю, то ж якщо що, можеш його перевідкрити чи створити нове.
> 
> 
>
