### ISSUE TITLE
Flag doesn´t show when using alternative layout.

### ISSUE THREAD

**Issue by azzz23** [zen-tools/gxkb#34]
When using 
```console
setxkbmap -model pc105 -layout us,cz_qwerty -option grp:alt_shift_toggle
```
question mark is shown.

![Screenshot_2021-05-03_14-06-35](https://user-images.githubusercontent.com/28875693/116876139-431d7d80-ac1c-11eb-8e41-fb2e1c0cdc41.png)

When using

```console
setxkbmap -model pc105 -layout us,cz -option grp:alt_shift_toggle
```
![Screenshot_2021-05-03_14-37-43](https://user-images.githubusercontent.com/28875693/116876575-ff774380-ac1c-11eb-83c2-776476e6c799.png)

flag is shown correctly.

**Comment by azzz23** [comment]
My bad there is already issue.

**Comment by zen-tools** [comment]
Hi, @tomasjanecky! I have removed `cz_qwerty.png` file in gxkb v0.9.1 while implementing #33. I guess, that was a mistake, so I will return it back in the next release. Until that, you can create a symlink on `cz.png` to fix an issue: 

```
$ mkdir -p ~/.local/share/gxkb/flags/
$ ln -s /usr/share/gxkb/flags/cz.png ~/.local/share/gxkb/flags/cz_qwerty.png
```

**Comment by azzz23** [comment]
Hi, yea i thought that  #33 solves this, my mistake.
