### ISSUE TITLE
Broken compatibility for appindicator package name

### ISSUE THREAD

**Issue by nick87720z** [zen-tools/gxkb#37]
From begining gxkb used "appindicator" with pkg-config and "libappindicator" in includes to use unity appindicator.
But then I see some debian patch, which is simply replacement for "appindicator" with "ayatana-indicator" everywhere. However, official sources seem still keeping original naming. I made it to build with that appindicator with this command before autogen:
```sh
{	find . -name '*.[ch]'
	echo configure.ac
} | xargs sed -i 's|ayatana-appindicator|appindicator|'
```
In particular, unmodified appindicator is used in gentoo. So, although sometimes they tell gentoo is strange, looks like this time it's debian broke something.

Although bug reports are usually expected to explain desired result - I see it's hard to tell, which naming way is preferable due to such divergence.

**Comment by zen-tools** [comment]
that's interesting, I will look if it is possible to add wrapper for both appindicator and ayatana-appindicator library.

**Comment by zen-tools** [comment]
I see that in Gentoo absent of libayatana-appindicator has [system-wide effect](https://bugs.gentoo.org/811078). Isn't it better to backport the [libayatana-appindicator](https://github.com/AyatanaIndicators/libayatana-appindicator) package to Gentoo? That would fix an issue not only for gxkb.

**Comment by nick87720z** [comment]
I just discovered, that there's different package: https://github.com/AyatanaIndicators/libayatana-appindicator
after search at packages.ubuntu.com.
However, they seem to be compatible - some packages, like remmina, simply try both as alternatives.

Perhaps, in this case nothing has to be changed for now. Imho, best way to handle this in distros would be to create alternatives entry for them in ubuntu / debian or eselect module in case of gentoo / portage - based distros.

**Comment by zen-tools** [comment]
Yes, I now recall, that old libappindicator is not maintained by anyone and that's why all depended on it software has to migrate on libayatana-appindicator. See this thread: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=895037

**Comment by nick87720z** [comment]
I just again looked to https://bazaar.launchpad.net/~indicator-applet-developers/libappindicator/trunk/files
did even check history, but looks like, only configure.ac has enough recent modification date, probably just to keep it building. Btw, gentoo ebuild for libappindicator takes sources from ubuntu sites:
```bash
MY_PV="${PV%_p*}"
PATCH_VERSION="${PV#*_p}"
SRC_URI="mirror://ubuntu/pool/main/liba/${PN}/${PN}_${MY_PV}+20.10.${PATCH_VERSION}.1.orig.tar.gz"
```
and PV, according to ebuild file name, is 12.10.1_p20200706.
Though it's hard for me to determind exact URI based on this "mirror://" schema.

**Comment by zen-tools** [comment]
I found some [libayatana-appindicator-0.5.5_p2.ebuild](https://data.gpo.zugaina.org/unity-gentoo/dev-libs/libayatana-appindicator/libayatana-appindicator-0.5.5_p2.ebuild), but it's still unclear why there is no official package... Or maybe I am looking in the wrong place, because I am not a Gentoo user

**Comment by nick87720z** [comment]
In Tue, 28 Dec 2021 09:25:04 -0800
ZEN ***@***.***> wrote:

> I found some
> [libayatana-appindicator-0.5.5_p2.ebuild](https://data.gpo.zugaina.org/unity-gentoo/dev-libs/libayatana-appindicator/libayatana-appindicator-0.5.5_p2.ebuild),
> but it's still unclear why there is no official package... Or maybe I
> am looking in the wrong place, because I am not a Gentoo user
> 

Looks like it's from unity-gentoo overlay. That overlay is in
eselect-repository, so at some degree it may be counted as official.
Almost like universe or multiverse sections for ubuntu (though not base
on licensing).

However, it seems to be treated as part of unity, not more. As for
unity-gentoo - gentoo wiki explains about unity, that its installation
in gentoo requires profile change, i.e. simple emerge is not enough
(would require too big changes in setup to be done manually).

I see no even reports about libayatana-appindicator at bugs.gentoo.org
(they would be if e.g. someone requested it to be packaged).

Btw, other package, building against libappindicator from main repo -
gnome-extra/gnome-shell-extension-appindicator .
