### ISSUE TITLE
Political decisions...

### ISSUE THREAD

**Issue by 029A-h** [zen-tools/gxkb#40]
Just sad about seeing functionality loss because of politics 😞
[Commit c93458256f924dd97efc23f3f3b510efc1f0a4c6](https://github.com/zen-tools/gxkb/commit/c93458256f924dd97efc23f3f3b510efc1f0a4c6)

**Comment by zen-tools** [comment]
Maybe, if you had read the obituaries every day, you would stop to call that a "political decisions"...

**Comment by kyak** [comment]
I'll be maintaining AUR package with Russian and Belarusian flags included: https://aur.archlinux.org/packages/gxkb-ru-by-flags.

@zen-tools thanks for the effort you've put into this software. It's your decision, and I have to respect that.
