### ISSUE TITLE
Icewm systray

### ISSUE THREAD

**Issue by shlozm** [zen-tools/gxkb#42]
The popup indicator (showing current layout or providing a menu on right-click) in Icewm taskbar system tray popups towards the bottom (where it can't be seen). I can only see it if I place the taskbar on top. Can this be fixed?
Thanks for a great application!

**Comment by zen-tools** [comment]
I can't reproduce the bug on liveCD with antiX. Even if I rebuild gxkb without libappindicator - the behavior is the same. Maybe the issue is in icewm's configuration?

![image](https://user-images.githubusercontent.com/3930413/219523637-2bb30785-46a6-45ff-8361-078ea8ae40f7.png)

**Comment by shlozm** [comment]
Thanks for the quick reply. I compiled the latest Icewm (3.3.1) on Debian stable. I fixed the issue for the meanwhile by setting the geometry explicitly in the Icewm winoptions file. I'll try to reproduce it in a VM to check that it's not hardware specific. I'll be back.

**Comment by shlozm** [comment]
Ok just checked with a vm install and it works. Must be hardware specific. I installed Debian on an old tablet...
