### ISSUE TITLE
Different flag image for different variants

### ISSUE THREAD

**Issue by jozsefk9** [zen-tools/gxkb#46]
What would be the way to have a different image displayed for **rs** and **rs -variant latin** ?

**Comment by zen-tools** [comment]
Hi Jozsef,

gxkb first looks for a file named `rs_latin.png`, then falls back to `rs.png` if it does not exist, and finally to `zz.png` if no files are found. You can add or override flags in your home directory, for example, rs(latin): `~/.config/gxkb/flags/rs_latin.png`.

**Comment by jozsefk9** [comment]
> Hi Jozsef,
> 
> gxkb first looks for a file named `rs_latin.png`, then falls back to `rs.png` if it does not exist, and finally to `zz.png` if no files are found. You can add or override flags in your home directory, for example, rs(latin): `~/.config/gxkb/flags/rs_latin.png`.

Fantastic! Thanks so much! This is actually the only way I can have this working in IceWM right now. And it's a beautiful way of doing it. So easy, so simple, so great! Perfect.
