### ISSUE TITLE
Ubuntu doesn't need a ppa

### ISSUE THREAD

**Issue by nazar-pc** [zen-tools/gxkb#7]
At least in Ubuntu 16.10/17.04 gxkb is present in default repositories, so there is no need to add ppa.
Maybe correct readme to reflect this fact?

**Comment by zen-tools** [comment]
As I know, the gxkb from default repositories compiled without an appindicator support. So, that version will work without the tray icon in Unity. Can you please check it?

**Comment by nazar-pc** [comment]
I have custom session, no Unity, so I can't do this on host system. But you can always spin a VM to double check.

**Comment by zen-tools** [comment]
Well, here is an answer:

```
$ gxkb -v
gxkb version 0.7.7
Features:
AppIndicator support - No
```

So, ppa is still required for Ubuntu users with Unity. I will add this information in README.md.

**Comment by nazar-pc** [comment]
BTW, just got 0.7.8 on 17.04. But still no AppIndicator.
Do you know why AppIndicator is not used? Maybe some potential issues?

**Comment by zen-tools** [comment]
Ubuntu has a cloned repository of Debian, where is changed build dependencies to compile without AppIndicator. I think, it was done because of absence the Unity in Debian.
