### ISSUE TITLE
Missing many flags

### ISSUE THREAD

**Issue by yselkowitz** [zen-tools/gxkb#9]
Flags for many countries/layouts are missing.  Personally, I'm looking for IL, but many more are missing.

**Comment by blonchkman** [comment]
hope this might help https://github.com/gosquared/flags (found among many other similar projects).

btw: many thanks to ZEN. This tool allow me the switch without any active settings-daemon.

**Comment by zen-tools** [comment]
Hi guys! Thanks for the feedbacks and sorry for the delay in response. Too much work and too less free time...

Regarding the issue, until proper fix is ready, I can offer the next workaround: the [shell script](https://github.com/zen-tools/gen-labels) to generate labels with country codes.

**Comment by yselkowitz** [comment]
Unfortunately, that isn't practical for packaging, as the text colours needed on a light-coloured panel differ from those needed on a dark-coloured panel.  @blonchkman's suggestion to used gosquared/flags (specifically, the 24x24 shiny icons with the ISO names, renamed to lower-case) works regardless.
